// export * from './Menu'
export { default as Menu } from './Menu.vue'
export { default as MenuTrigger } from './MenuTrigger.vue'
export { default as MenuContent } from './MenuContent.vue'
export { default as MenuGroup } from './MenuGroup.vue'
export { default as MenuItem } from './MenuItem.vue'
import './Menu.scss'
